databases:
  - name: vitox-db
    databaseName: vitox
    user: vitox_user
    plan: free

services:
  - type: web
    name: vitox-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ADMIN_EMAIL
        value: junaidshah78634@gmail.com
      - key: DATABASE_URL
        value: "${DATABASE_URL}"
